---
title: "Chocolats Pralinés"
format: html
editor: visual
---

Liens vers la recette originale :\
<https://www.meilleurduchef.com/fr/recette/croustillant-praline.html>

## Ingrédients 

-   240g de noisettes

-   

Le praliné et l'intérieur praliné se préparent la veille.\
Le chablonnage et le glaçage se font le landemain.

Il faut préparer les chocolats en avance pour qu'ils aient le temps de s'armoniser.\
Ex. samedi étape 1 / dimanche étape 2, on déguste 48 / 72h plus tard.

## Praliné noisette

-   55 g d'eau (1/2 = 27.5g)

-   220 g de sucre en poudre (1/2 = 110g)

-   275 g de noisettes entières (1/2 = 137.5g) \| 165g si seules)

-   55 g d'amandes entières (1/2 = 27.5g)

::: callout-note
Le mix noisette / amande est selon convenance.\
On peut ne mettre que des noisettes.
:::

### Torréfaction

Torréfier les noisettes / amandes au four 180°C pendant 5 minutes.\
Mettre les noisettes dans un torchon et les faire rouler pour enlever la peau.\
Peser les différentes quantités et réserver.

### Caramel

Verser l'eau et le sucre en poudre dans une casserole.\
Porter à ébullition et monter le sirop à 118°C (thermomètre sonde).

A 118°C, ajouter les noisettes et amandes entières.\
Mélanger avec le sirop qui va masser autour et devenir blanchâtre !\
Continuer la cuisson en remuant, la pellicule de sucre se transforme de nouveau en sirop, puis en camarel. Ne pas laisser brunir trop longtemps, sinon le caramel aura un goût amer.

::: callout-tip
Quand le sucre cristalise autour des noisettes dans la casseroles, il faut que le feu soit chaud pour que ça redevienne du caramel sans que ça dure trop longtemps.

Plaque induction 9 positions : 6 / 7 sinon le sucre reste cristalisé, éviter de monter à 8 pour ne pas brûler le caramel !

Plutôt dans une poelle car le sucre critalise sur les bords dans une casserole et c'est plus compliqué à faire fondre (plus de perte).
:::

Verser les noisettes / amandes caramélisées sur une feuille de papier cuisson et laisser refroidir à température ambiante.

### Praliné

Placer les noisettes / amandes caramélisées dans un mixeur (il faut qu'il soit assez puissant).\
Mettre en marche à vitesse minimum pour concasser les noisettes caramelisées.

Il faut un certain temps pour obtenir une pâte lisse (\>10 min) : on va passer de noisettes concassées à un mélange pâteux, puis finalement à un pâte souple quand la température monte et que l'huile des fruits secs ressort. Si besoin, arrêter le mixeur pour remettre de la matière au milieu.

Réserver dans un bocal (type pot à confiture).

::: callout-tip
Peser la quantité exacte dans le bocal pour la phase intérieur praliné.
:::

## Intérieur praliné

-   210 g de fèves de chocolat noir (Caraïbe à 66%) (1/2 = 105g)

-   8 g de beurre de cacao (je n'en mets pas...)

-   550 g de praliné noisette (1/2 = 275g)

-   50 g de noisettes hachées et grillées (1/2 = 25g)

Faire fondre le chocolat (au bain marie, doucement et avec le thermomètre).\
Une fois fondu, le mélange doit titrer environ 45°C (+ ou - 1°C).

Pendant ce temps, hacher les noisettes.

Ajouter au chocolat fondu les 275 g de praliné noisette qu'il faudra peser au gramme près (d'où l'intérêt de le peser avant).

Ajouter les noisettes hachées / torréfiées.\
Mélanger soigneusement à la maryse, jusqu'à l'obtention d'une préparation homogène.

Prendre un carré inox 16 x 16 cm (ou autre, plaque silicone).\
Filmer un des côté avec un film plastique (bien tendre pour qu'il adhère sur les côtés).\
Poser le carré sur une plaque / papier cuisson.

Verser la préparation dans le carré.\
J'utilise d'autres plaques en complément comme le mien est trop petit.

Laisser refroidir à température ambiante jusqu'au lendemain (couvrir).

## Chablonnage

-   80 g de fèves de chocolat noir (Caraïbe à 66%) (1/2 = 40g)

Vérifier si l'intérieur praliné est encore souple au toucher.\
Si c'est le cas, le placer 30 minutes au réfrigérateur pour le raffermir.

Faire fondre le chocolat (bain marie, doucement)

Pendant ce temps, démouler le cadre en passant une lame de couteau.

Avec un pinceau, déposser une couche de chocolat sur une face.\
Si le chocolat est un peu frais, ça va figer assez vite.\
Retourner et faire la seconde face.

Une fois le chocolat figé, découper en carrés / rectangles.\

## Glaçage

La recette d'origine a deux glaçages.\
Je n'en retiens qu'un donc les quantités sont inchangées.

-   250 g de fèves de chocolat (Caraïbe à 66%)

-   37 g d'huile de pépins de raisins

-   50 g de praliné grains (facultatif)

Faire fondre le chocolat.

Ajouter l'huile de pépins de raisins

Ajouter le praliné grains

Tremper les morceaux d'intérieur praliné dans le chocolat.\
Déposer sur une feuille de papier cuisson.

On peut déposer une garniture sur le chocolat avant qu'il ne fige.

# Notes

Quantités divisées par 2\
Uniquement enrobage chocolat noir (avec les mêmes quantités donc pour cette partie)

Test 1 : \
ça donne 1 moule souple marron + 23 cases de la plaque bleu (5 rang + 3 cases)

Test 2 :\
un carré 10 x 10cm + une plaque silicone
