---
title: "Pickles d'oignons Rouges"
format: html
editor: visual
---

# Pickles d'oignons rouges

Simple, facile et rapide à préparer.\
A utiliser comme un condiment pour accompagner un plat, une salade, un sandwich.

Le choix des épices est sélon les goûts.\
Ici on part sur une base poivre / piment / gingembre pour avoir quelque chose d'un peu relevé.

## Ingrédients

-   1 oignon rouge

-   Vinaigre (de vin, de cidre, ...)

-   1 cc. de sucre roux (cassonade)

-   Epices au choix (gingembre, poivre, piment)

-   Alcool type cognac, armagnac

-   Huile d'olive

::: callout-note
On ne met pas de sel car on part du principe qu'il y en aura déjà dans le plat accompagné.

La quantité de vinaigre dépend du résultat visé.\
Une petite quantité suffit à créer le constraste, mais on peu aussi les conserver dans le vinaigre...
:::

## Préparation

Peler l'oignon et le découper.\
Pas trop fin, il faut un peu de consistance pour garder du croquant à la cuisson.

Chauffer une poelle avec un filet d'huile d'olive.\
Faire revenir l'oignon à feu vif pendant un instant puis baisser pour éviter qu'il ne cuisse trop.

Ajouter les épices.\
Ajouter l'alcool pour déglacer une première fois.\
Ajouter le vinaigre pour déglacer une seconde fois.\
Baisser à feu doux et remuer pour récupérer les sucs de cuissons.

Ajouter le sucre.

Verser dans un bocal type pote à confiture et fermer immédiatement avec le couvercle.\
Conserver à température ambiante le temps de refroidir.

Conserver au frigo ensuite.

## Utilisation

On peut utiliser les pickles d'oignon rouge en condiment dans un sandwich (comme un cornichon), en accompagnement (toping) dans une salade ou même un plat.
