---
title: "Travers de Porc Cuisson Lente"
format: html
editor: visual
---

## Ingrédients

-   1 travers de porc (en fonction du nombre de personne)

-   2 c. à soupe de miel

-   2 c. à soupe de sauce soja

-   1 c. à soupe d’huile d’olive

-   2 gousses d’ail hachées

-   1/2 c. à soupe de gingembre frais râpé

-   1/2 c. à café de paprika fumé

-   Sel et poivre

## Préparation

-   **Préparez vos travers de porc :** Retirez la fine membrane située au dos des travers de porc. Cette action garantit une meilleure pénétration des aliments et une texture plus tendre après cuisson.

-   **Préparez la marinade :** Dans un bol, mélangez le miel, la sauce soja, l’huile d’olive, l’ail, le gingembre et le paprika. Salez et poivrez selon vos goûts. Fouettez bien pour obtenir une sauce homogène.

-   **Marinez la viande :** Placez les travers dans un plat. Badigeonnez-les généreusement avec la marinade, en vous assurant qu’ils soient bien enrobés. Couvrez avec un film alimentaire et laissez reposer au réfrigérateur **pendant au moins 2 heures, idéalement toute la nuit**.

## Cuisson

-   **Cuisez lentement au four :** Préchauffez le four à 150 °C. Couvrez le plat de papier alu pour conserver l’humidité et **enfournez durant 3 heures**. Cette cuisson lente à basse température rendra la viande extrêmement tendre.

-   **Caraméliser les travers :** Retirez le papier alu. Augmentez la température du four à 200 °C. Badigeonnez à nouveau les travers avec le reste de la marinade et laissez-les caraméliser durant 10 à 15 min.

-   **Vérifiez la cuisson :** La viande doit se détacher facilement de l’os. Si nécessaire, laissez cuire quelques instants de plus.

-   **Laissez reposer et servez :** Sortez les travers du four et laissez-les reposer pendant 5 min avant de servir. Accompagnez-les de pommes de terre rôties, de légumes grillés ou d’une salade croquante.

## Accompagnements

-   **Pommes de terre et carottes fondantes** :\
    Cuisez-les au four en papillote avec du beurre et des herbes.
