---
title: "Velouté de courgettes"
format: html
editor: visual
---

En entrée ou en verrine.\
S'accompagne parfaitement bien avec des éclats de charcuterie secs.

## Ingrédients

-   2 / 3 courgettes bio (on garde la peau)

-   Vin blanc sec

-   80 ml de crème liquide

-   Estragon

-   Epices (poivre, curry)

-   1 tranche de pain de mie blanc (sec ou passer au grille pain pour le secher)

## Préparation

Laver et couper grossièrement les courgettes.

Chauffer une casserole avec un filet d'huile d'olive.\
Mettre les courgettes et laisser revenir quelques minutes en remuant de temps en temps.

Baisser le feu. Ajouter le vin pour déglacer.\
Ajouter l'assaisonnement.\
Ajouter de l'eau à mi-hauteur.

Couvrir et laisser cuire à feu doux pendant 20 minutes.

Mettre la crème liquide à chauffer dans une poelle.\
Quand elle est chaude, ajouter l'estragon.\
Ajouter des épices (curry, curcuma).\
Laisser réduire à feu doux en remuant.

Quand la consistance est bonne, arrêter le feu et laisser refroidir.

Verser l'eau de cuisson des courgettes dans un verre.

Mettre les courgettes aux mixeur, lancer au minimum.\
Ajouter la crème infusée à l'estragon.\
Ajouter la mie sèche, ajuster la vistesse du mixeur si besoin (on veut un mouvement)

On peut utiliser l'eau de cuisson pour ajuster la consistance.

## Notes

Je trouve que c'est un peu gras, essayer 40 ml
